# OAuth token to tell twitch who you are (so you can unlock emotes).
#
# To get the token, follow the steps:
# 1. In the browser login to twitch.tv with your account
# 2. Right click in the browser and click 'Inspect'
# 3. Click the 'Network' tab
# 4. There should be a 'Filter' input box, type gql in there
# 5. Click one of the remaining rows, if there is no row, hit F5 once,
#    and then click one of the rows
# 6. More details and tabs for the row will appear. Click the Headers tab.
# 7. Scroll down to find 'Authoriation: OAuth BLABLABLABLABLA' in the
#    Request Headers section. 'BLABLABLABLABLA' is what you have to fill
#    in here
#
# Note: If you prefer to use an environment variable instead, you can
#       leave this config value empty and instead put the token into the
#       environment variable `TWITCH_OAUTH_TOKEN`
oauth_token = ""

# This one is hardcoded by twitch, and it should not be required to
# be changed.
# To confirm the correctness of this value, you can go to twitch.tv
# and look at the website source, search for 'clientId="' and the value
# right after that should match this value here
twitch_client_id = "kimne78kx3ncx6brgo4mv6wki5h1ko"


# Define channels in which you want which emotes to be unlocked
# note that the emotes have to be actually unlockable by channel points
[[twitch_channels]]
# The channel name
name = "nc_para_"

# The emotes that should be unlocked for that channel
emotes = ["ncpara1Love", "ncpara1Foxy"]

# The number of tries until the script gives up unlocking emotes.
# This is only used when the 'Unlock a random Sub Emote' has to
# be used.
# Optional, defaults to 1
random_tries = 5


# Add more channels by adding blocks like these:
# [[twitch_channels]]
# name = "kitboga"
# emotes = ["bogaShh", "bogaChamp"]
# random_tries = 5
